name: Discord Webhook Notify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: Build success!
      - name: Fail
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Build failed!